// Assembles <design>/handoff/, what an implementer needs: the component files,
// tokens, screenshots of the approved previews, the brief and the decisions.
// The agent writes GUIDE.md there itself; everything else is regenerated on
// each run.
import { copyFileSync, existsSync, lstatSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, extname, join } from "node:path";
import { STAGES } from "../server/round.mjs";
import { importedAssets } from "../server/preview.mjs";
import { previewsOf, shoot } from "./shots.mjs";
import { tokensJson } from "./tokens.mjs";

export const GUIDE = "GUIDE.md";
const SCRIPTS = [".jsx", ".tsx", ".js", ".ts"];

// Regular files under dir, relative to base with "/" separators. Symlinks
// are skipped: one could point at the session token or outside the design.
function files(base, rel) {
  const dir = join(base, ...rel.split("/"));
  if (!existsSync(dir) || !lstatSync(dir).isDirectory()) return [];
  return readdirSync(dir).sort().flatMap((name) => {
    const st = lstatSync(join(dir, name));
    return st.isDirectory() ? files(base, `${rel}/${name}`) : st.isFile() ? [`${rel}/${name}`] : [];
  });
}

function copy(designDir, out, rel) {
  const to = join(out, ...rel.split("/"));
  mkdirSync(dirname(to), { recursive: true });
  copyFileSync(join(designDir, ...rel.split("/")), to);
}

const quote = (s) => `"${String(s).split("\n")[0]}"`;

export async function handoff(designDir, { rounds, decisions }) {
  const out = join(designDir, "handoff");
  mkdirSync(out, { recursive: true });
  for (const name of readdirSync(out)) if (name !== GUIDE) rmSync(join(out, name), { recursive: true, force: true });
  const written = [];

  // The component files as they are now, with the images and fonts they
  // import, so the folder builds on its own.
  const ui = files(designDir, "ui");
  const assets = await importedAssets(designDir, ui.filter((f) => SCRIPTS.includes(extname(f))));
  if (assets.some((a) => a.startsWith("assets/web/")) && existsSync(join(designDir, "assets", "web", "SOURCES.md"))) assets.push("assets/web/SOURCES.md");
  for (const rel of [...ui, ...assets]) copy(designDir, out, rel);
  if (ui.length) written.push("ui/");
  if (assets.length) written.push("assets/");

  if (existsSync(join(designDir, "ui", "tokens.css"))) {
    writeFileSync(join(out, "tokens.json"), JSON.stringify(tokensJson(readFileSync(join(designDir, "ui", "tokens.css"), "utf8")), null, 2) + "\n");
    written.push("tokens.json");
  }
  if (existsSync(join(designDir, "context.md"))) {
    copyFileSync(join(designDir, "context.md"), join(out, "brief.md"));
    written.push("brief.md");
  }

  // The latest reaction on each item counts; a draft is approved while its
  // latest verdict is "approve". Each stage hands off its latest approved draft.
  const latest = new Map();
  for (const d of decisions) if (!("comment" in d)) latest.set(`${d.round}\u0000${d.item}`, d.value);
  const approvedIn = (stage) => rounds.filter((r) => r.stage === stage && r.kind === "draft" && latest.get(`${r.id}\u0000draft`) === "approve").at(-1);
  const stages = STAGES.map((stage) => ({ stage, round: approvedIn(stage) }));

  const previews = stages.flatMap(({ round }) => (round ? previewsOf(round).map((b) => ({ round, b })) : []));
  let shots = [];
  for (const round of new Set(previews.map((p) => p.round))) {
    shots.push(...await shoot(designDir, previews.filter((p) => p.round === round).map((p) => p.b), { outDir: join(out, "shots", round.id) }));
  }
  if (shots.length) written.push("shots/");

  const answers = rounds.flatMap((r) => (r.pages ?? []).flatMap((p) => p.blocks)
    .filter((b) => b.type === "question" && b.choices && latest.has(`${r.id}\u0000${b.id}`))
    .map((b) => {
      const v = latest.get(`${r.id}\u0000${b.id}`);
      return `- ${r.id}/${b.id} ${quote(b.text)}: ${Array.isArray(v) ? v.join(", ") || "(none)" : v}`;
    }));
  writeFileSync(join(out, "decisions.md"), [
    "# Decisions",
    "",
    "| Stage | Approved draft |",
    "| --- | --- |",
    ...stages.map(({ stage, round }) => `| ${stage} | ${round ? `${round.id} ${quote(round.title)}` : "not approved"} |`),
    "",
    "## Answers",
    "",
    ...(answers.length ? answers : ["None."]),
    "",
  ].join("\n"));
  written.push("decisions.md");

  const has = (f) => written.includes(f);
  const lines = [
    `# Handoff: ${designDir.split(/[\\/]/).pop()}`,
    "",
    `Generated by \`mockup handoff\` on ${new Date().toISOString().slice(0, 10)}. Start with ${GUIDE}.`,
    "",
    `- ${GUIDE}: how to build this design into the app, and what is still open`,
    ...(has("brief.md") ? ["- brief.md: the approved brief"] : []),
    "- decisions.md: the approved draft of each stage, and the user's answers",
    ...(has("tokens.json") ? ["- tokens.json: the design tokens from ui/tokens.css, in the W3C Design Tokens format; dark values under $extensions.mockup.modes"] : []),
    ...(has("ui/") ? ["- ui/: tokens.css, one React component per file in components/, and the pages that compose them"] : []),
    ...(has("assets/") ? ["- assets/: images and fonts the components import" + (assets.some((a) => a.startsWith("assets/web/")) ? "; assets/web/ holds third-party images, see SOURCES.md for their licenses" : "")] : []),
    ...(has("shots/") ? ["- shots/: screenshots of the approved previews, `<item>.<device>.<theme>.png`"] : []),
    "",
  ];
  writeFileSync(join(out, "README.md"), lines.join("\n"));
  written.unshift("README.md");
  return { dir: out, written, shots, guide: existsSync(join(out, GUIDE)) };
}
